services:
  php:
    build: .
    volumes:
      - ./php:/var/www/html
    expose:
      - 9000

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      - db
    ports:
      - "9000:9000"
      - "9092:9092" 
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: admin
      SONAR_JDBC_PASSWORD: "2103295@sit.singaporetech.edu.sg"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  git-server:
    container_name: git-server
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
     - git_data:/home/git

  db:
    image: postgres:latest
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: admin	
      POSTGRES_PASSWORD: "2103295@sit.singaporetech.edu.sg"
      POSTGRES_DB: sonarqube
    volumes:
      - postgresql:/var/lib/postgresql

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  git_data:

networks:
  default:
    name: test
