name: OWASP Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'MyProject'
          path: '.' # Scan the current directory
          format: 'HTML'

      - name: Upload scan report
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check-Report
          path: reports